name: Valhalla Forest
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5701631538104266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e9373'
    - '#3b722e'
    - '#0b0c0e'
    - '#e9eefd'
    - '#aab0dc'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
